    #config file for gesture module
 
HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.5
MAX_NUM_HANDS = 1

#gesture rec thresholds
FINGER_TIP_THRESHOLD = 0.02
PINCH_THRESHOLD = 0.05
FIRST_THRESHOLD = 0.15

#Scrolling
SCROLLING_SENSITIVITY = 2.0
SCROLL_AMOUNT = 40  #pixels per scroll action

#cooldown time in frames
GESTURE_COOLDOWN_FRAMES = 10

SMOOTHING_FACTOR = 0.7

FRAME_WIDTH = 640
FRAME_HEIGHT = 480

#debug
SHOW_LANDMARKS = True
SHOW_CONNECTIONS = True
SHOW_BOUNDING_BOX = False

class HandLandmark:
    WRIST = 0
    THUMB_CMC = 1
    THUMB_MCP = 2
    THUMB_IP = 3
    THUMB_TIP = 4
    INDEX_FINGER_MCP = 5
    INDEX_FINGER_PIP = 6
    INDEX_FINGER_DIP = 7
    INDEX_FINGER_TIP = 8
    MIDDLE_FINGER_MCP = 9
    MIDDLE_FINGER_PIP = 10
    MIDDLE_FINGER_DIP = 11
    MIDDLE_FINGER_TIP = 12
    RING_FINGER_MCP = 13
    RING_FINGER_PIP = 14
    RING_FINGER_DIP = 15
    RING_FINGER_TIP = 16
    PINKY_MCP = 17
    PINKY_PIP = 18
    PINKY_DIP = 19
    PINKY_TIP = 20